# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Universal Tape
tagline:          'An open standard mortgage note tape format'
description:      'An open standard mortgage note tape format'
url:              http://universaltape.org
baseurl:          /

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/UniversalTape/universaltape.org
